### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by diegosiqueir4** [UB-Mannheim/kitodo-production-docker#1]
I think the README should be updated to clarify that this repository does not use anymore the container: `kitodo/database:latest`, and to include instructions to actually run the `kitodo/production` Docker image.

**Comment by jmechnich** [comment]
Hi there,

branch release-3.x has been made the default branch with an updated README file. The other branches will be updated in time (or deleted if obsolete).

Regards,
Jörg

**Comment by diegosiqueir4** [comment]
Hello Jörg,

I am grateful for your help.

Best regards,
Diego
