### ISSUE TITLE
[Feature Request] Docker image for Kitodo.Production 3.1.0

### ISSUE THREAD

**Issue by diegosiqueir4** [UB-Mannheim/kitodo-production-docker#2]
Do you plan in the near future to release a Docker image with the latest Kitodo release?
- [Kitodo.Production 3.1.0](https://github.com/kitodo/kitodo-production/releases/tag/kitodo-production-3.1.0) - `Latest release`: (March 2, 2020)

Thank you in advance!

**Comment by jmechnich** [comment]
An updated image is available from Docker Hub or can be built using the v3.1.0 tag.

**Comment by diegosiqueir4** [comment]
Thank you, Jörg,

I tested both options and they worked perfectly for me.

Best regards,
Diego
